version: '3.7'

services: 
  iris:
    init: true
    image: containers.intersystems.com/intersystems/iris-community:2021.1.0.215.3
    hostname: iris
    ports:
    - 52773:52773
    - 1972:1972
    environment:
    - ISC_CPF_MERGE_FILE=/ISC/merge.cpf
    volumes:
    - .:/ISC  